version: "3.9"

services:
  react:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
